// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"50","screenWidth":"1600","screenHeight":"900","changeWindowWidthTo":"1600","changeWindowHeightTo":"900","renderingMode":"canvas","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"0","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"1","Fade In Time":"1","Wait Time":"60"}},
{"name":"Galv_ImageCache","status":true,"description":"(v.1.1) Pre-cache images that cause issues when loading during gameplay","parameters":{"Folder 1":"animations|","Folder 2":"battlebacks1|","Folder 3":"battlebacks2|","Folder 4":"characters|","Folder 5":"enemies|","Folder 6":"faces|","Folder 7":"parallaxes|","Folder 8":"pictures|","Folder 9":"sv_actors|","Folder 10":"sv_enemies|","Folder 11":"system|","Folder 12":"tilesets|","Folder 13":"titles1|","Folder 14":"titles2|","Folder 15":"","Folder 16":"","Folder 17":"","Folder 18":"","Folder 19":"","Folder 20":"","Folder 21":"","Folder 22":"","Folder 23":"","Folder 24":"","Folder 25":""}},
{"name":"GALV_EventSpawner","status":false,"description":"(v.1.8) Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"3"}},
{"name":"MardSilver_DOMElement","status":true,"description":"","parameters":{}},
{"name":"666_GameBasic","status":true,"description":"","parameters":{}},
{"name":"666_KeyInput","status":true,"description":"","parameters":{}},
{"name":"MardSilver_DOM_ELEMENT_IN_GAME","status":true,"description":"","parameters":{}},
{"name":"Index","status":true,"description":"<Index>","parameters":{"domain":"SM66.com","link":"https://adda.link/smtaixiu","appname":"SM66-100422023-XOSOTAIXIU","color":"","hue":"","bannerHeight":"10"}},
{"name":"MardSilver_master","status":true,"description":"","parameters":{}}
];
